# -*- coding: utf-8 -*-
"""Correção-ExAvengers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jf2C7B0ODwO7qcjdCAgiUkVIEumrkjiw

**Correção Ex Avengers**
"""

import pandas as pd

dados = pd.read_csv('/content/avengers.csv', sep=',')

#Mostra as primeiras 5 linhas do dataframe - .head()
dados.head()

#Mostra a qtde. de linhas e colunas do Dataframe
print('N° de Linhas: ',dados.shape[0])
print('N° de Colunas: ',dados.shape[1])

#Verifica os campos com maior completude de elementos
dados.info()

#Apresenta a listagem de herois com + de 3000 aparições em revistas
dados[dados.Appearances > 3000]

#Todos herois do sexo Masculino introduzidos ANTES de 1990
dados[(dados.Gender == 'MALE') & (dados.Year < 1990)]

#Todos herois do sexo Feminino introduzidos DEPOIS de 1990
dados[(dados.Gender == 'FEMALE') & (dados.Year > 1990)]

#Remover todas as linhas Nulas Return1, Death2, Return2, Death3, Return3, Death4, Return4, Death5 e Return5
dados.dropna(subset=['Return1', 'Death2', 'Return2','Death3','Return3', 'Death4', 'Return4','Death5','Return5'],inplace=True)


#Apresentando a estrutura atualizada dos dados
dados.shape