# -*- coding: utf-8 -*-
"""Aula05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BaaHQIc4p8Bin93AZCZmZu_lKJ-QlGCx

# Inserindo dados aleatórios.

#Medidas de Tendência Central
"""

#Média Aritmética
import numpy as np
from math import sqrt



listaNotas = np.arange(3)
#print('Notas: ',listaNotas)

soma = np.sum(listaNotas)
#print(soma)

#Usando o atributo da variavel (.SIZE) pois é mais automatizado que o LEN()
media = soma/listaNotas.size
print(f'Média Aritmética: {media:.2f}')

#Média Ponderada
pesos = [1,2,3]

#Forma automatizada (average - media aritm. / weights - pesos)
mediaPonderada = np.average(listaNotas, weights=pesos)
print(f'Média Ponderada: {mediaPonderada:.2f}')


#MÉDIA GEOMÉTRICA ----------------------------------------------

lista = np.arange(2)
lista[0] = 8
#print('Lista:' ,lista)
'''for i in lista:
  produto = produto * i'''

produtos = np.prod(lista)
#print('Produto lista: ',produtos)
print(f'Média Geométrica: {sqrt(produtos):.2f}')
#Calculo para qualquer tamanho de lista
print(f'Média Geométrica: {(produtos)**(1/lista.size):.2f}')

#MÉDIA HARMÔNICA ---------------------------------------------------

from scipy.stats import hmean
listaH = np.arange(2)
listaH[0] = 8
listaH[1] = 4
harmonica = hmean(listaH)
print(f'Média Harmônica: {harmonica:.2f}')

#MEDIANA -------------------------------------------------------------
#Representa o valor que está no meio da lista
listaMediana = [1,2,4,4,4,5,6,7]
mediana = np.median(listaMediana)
print('Mediana: ',mediana)

#MODA ----------------------------------------------------------------
# É o elemento que aparece mais vezes
from scipy.stats import mode

listaModa = [1,2,4,4,4,5,6,7]
print('Moda: ',mode(listaModa))

"""DESVIO PADRÃO

"""

#DESVIO PADRÃO
import numpy as np
import math

lista = np.arange(10)
print("Lista: ",lista)
media = np.average(lista)

listaMenosMedia = lista-media
print('Lista Menos Média: ',listaMenosMedia)

listaAoQuadrado = listaMenosMedia ** 2
print('Lista ao Quadrado: ', listaAoQuadrado)

somatorio = np.sum(listaAoQuadrado)
print('Somatório: ',somatorio)

divisao = somatorio/lista
print('Divisão: ',divisao)

raiz = (divisao)**(1/2)
print(f'Desvio Padrão: {raiz}')

"""NÚMEROS ALEATÓRIOS"""

import numpy as np
#Biblioteca para plot de Gráficos
from matplotlib import pyplot

#LISTAS ALEATÓRIAS
lista = np.random.randint(100, size=500)
#print('Lista: ',lista)

# Gera um HISTOGRAMA da lista
pyplot.hist(lista)
#pyplot.show mostra o Gráfico
pyplot.show()

#COMPORTAMENTO NORMAL com baixa distribuição

lista = np.random.normal(100,20, size=500)
#print(lista)

pyplot.hist(lista)
pyplot.show()

#COMPORTAMENTO NORMAL com alta distribuição

lista = np.random.normal(100,80, size=500)
#print(lista)

pyplot.hist(lista)
pyplot.show()