# -*- coding: utf-8 -*-
"""Aula08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzNr4igH3o39yNUB7MvLk9o7Dt17ruWQ

**Medidas Separatrizes**
"""

import pandas as pd

dados = pd.read_csv('/content/dados_censo2015.csv')

#Retorna a Mediana de cada uma das colunas
dados.quantile()

#Define o Quantil que eu quero :
# 1° Quartil 25%
dados.quantile(0.25)
# 2° Quartil 50%
dados.quantile(0.50)
# 3° Quartil 75%
dados.quantile(0.75)

#Retorna para cada uma das minhas colunas meus quantis
quantis = dados.quantile([.25,.50,.75], axis=0)
quantis

#Transpor a tabela
quantisTranspost = quantis.T
quantisTranspost

#Decis
listaDecis = []

for i in range(1,10):
  listaDecis.append(i/10)
  print(i)
print(listaDecis)

quantis = dados.quantile(listaDecis, axis=0)
quantis

import seaborn as sns
import matplotlib.pyplot as plt

g1 = sns.displot(dados.Idade, bins=10)
g1



#Mostra a frequencia Acumulada dos dados
g1Cumulativo = sns.displot(dados.Idade, bins=10, cumulative=True)
g1Cumulativo

#Diferencia os dados pelo sexo
g1Cumulativo = sns.displot(data=dados, x='Idade',bins=10, hue='Sexo' ,cumulative=True)
g1Cumulativo

#Boxplot
b1 = sns.boxplot(data=dados, x='Idade', orient='h', color='red')

#Distribuição da altura de acordo com sexo - 0 = Masc. / 1 = Fem.
b2 = sns.boxplot(data=dados, x='Altura', y='Sexo', orient='h')

#Distribuição por Renda
b3 = sns.boxplot(data=dados, x='Renda', orient='h')

#Renda abaixo de 20mil
b3 = sns.boxplot(data=dados[dados.Renda < 20000], x='Renda', orient='h')

#Distribuição de sexo e renda - 0 = Masc. / 1 = Fem.
b4 = sns.boxplot(data=dados[dados.Renda < 20000], x='Renda',y='Sexo' , orient='h')

#Renda por Anos de Estudo
b5 = sns.boxplot(data=dados[dados.Renda < 20000], x='Renda',y='Anos de Estudo' , orient='h')

#Sexo por Anos de Estudo - 0 = Masc. / 1 = Fem.
b6 = sns.boxplot(data=dados[dados.Renda < 20000], x='Anos de Estudo',y='Sexo' , orient='h')