# -*- coding: utf-8 -*-
"""ExRevisão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6P9dsic43enioD-7ZY3R-hB6gH7xWNw

EXERCÍCIOS DE REVISÃO

Ex Aula 08
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

fipe = pd.read_csv('/content/tabela_fipe.csv')
fipe.head()

g1 = sns.boxplot(x='Valor',data=fipe[fipe.Valor < 500000], orient = 'h', color = 'green')
g1.set_title('Valores - FIPE',fontsize=18)
g1.figure.set_size_inches(14,5)

fipe[fipe.Valor > 4000000]