# -*- coding: utf-8 -*-
"""Aula 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORtJGpdQU7k3UpvZNG3YyV6idcZK3n08

#USANDO BIBLIOTECA NUMPY
"""

import numpy as np

print('Lista ordenada de valores:')

listaOrdenada= np.arange(10)
print(listaOrdenada)

"""# Arrays

Arrays listas com operações matemáticas.

Realiza a operação em todos os valores da lista.
"""

valoresDeCarros = np.array([5000,10000,15250,20000])
valoresDeCarros = valoresDeCarros + 1500
print('Valores somados a 10:', valoresDeCarros)

valoresDeCarros = valoresDeCarros * 2
print('Valores multiplicados por 2:',valoresDeCarros)

"""# IMPORTANDO ARQUIVO TXT"""

import numpy as np

#importando o aquivo txt com a função loadtxt do numpy
valores = np.loadtxt('carros-valor.txt')
valores = np.array(valores)
valores = valores*0.9
print(valores)


